services:
  runner:
    build:
      context: .
      target: development  # 改为使用development阶段镜像
    command: npm run dev
    volumes:
      - .:/home/appuser/app
      - /home/appuser/app/node_modules  # 避免本地node_modules覆盖容器内依赖
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=debug
      - BROWSER_HEADLESS=false
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    # user: "node"  # 注释掉，使用镜像中默认的appuser用户（避免权限冲突）

  # 生产环境服务不变，仍使用production阶段
  runner-prod:
    build:
      context: .
      target: production
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LOG_LEVEL=info
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis-data:
